sudo: false
dist: xenial
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- "3.6"
- "3.7"
install:
- pip install --upgrade pip wheel
- curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
- make install
script:
- make test
